# Generated by Django 4.1.4 on 2022-12-15 09:52

from django.db import migrations

from shop14.models import Customer


def forward_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CustomerModel = apps.get_model("shop14", "Customer")
    customers = CustomerModel.objects.using(db_alias).all()
    for customer in customers:
        customer.customer_type = (
            Customer.CustomerType.PREMIUM
            if customer.is_premium
            else Customer.CustomerType.FREE
        )


def backward_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CustomerModel = apps.get_model("shop14", "Customer")
    customers = CustomerModel.objects.using(db_alias).all()
    for customer in customers:
        is_premium = customer.customer_type == Customer.CustomerType.PREMIUM
        customer.is_premium = is_premium
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shop14", "0016_customer_customer_type"),
    ]

    operations = [migrations.RunPython(forward_func, backward_func)]
