# Generated by Django 4.1.4 on 2022-12-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop07", "0004_migrate_shipping_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="shipping_state",
        ),
    ]
