# Generated by Django 4.1.4 on 2023-01-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.CharField(max_length=250),
        ),
    ]
