# Generated by Django 4.1.4 on 2022-12-08 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_tweet_text_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="related_tweet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
